/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import DataStructures.tree.FizzBuzzTree;
import DataStructures.tree.TreeNode;

import static DataStructures.tree.FizzBuzzTree.fizzBuzzTree;

public class App {


    public static void main(String[] args) {
        TreeNode root = new TreeNode("1");
        root.getChildren().add(new TreeNode("3")); // Fizz
        root.getChildren().add(new TreeNode("5")); // Buzz
        root.getChildren().add(new TreeNode("15")); // FizzBuzz

        // Apply FizzBuzz transformations
        TreeNode modifiedTree = FizzBuzzTree.fizzBuzzTree(root);

        // Display the modified tree values
        displayTree(modifiedTree);
    }

    // A method to recursively display the tree
    private static void displayTree(TreeNode node) {
        if (node == null) {
            return;
        }

        System.out.println(node.getValue());

        for (TreeNode child : node.getChildren()) {
            displayTree(child);

        }
    }
}