/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;
import java.util.List;

public class App {
    public static void main(String[] args) {
        Graph graph = new Graph();

        // Add nodes and edges to the graph
        Node node1 = new Node(1);
        Node node2 = new Node(2);
        Node node3 = new Node(3);
        Node node4 = new Node(5);
        Node node5 = new Node(4);
        Node node6 = new Node(9);


        node1.neighbors.add(node2);
        node1.neighbors.add(node3);
        node2.neighbors.add(node3);
        node2.neighbors.add(node4);
        node2.neighbors.add(node5);
        node2.neighbors.add(node6);

        graph.addNode(node1);
        graph.addNode(node2);
        graph.addNode(node3);
        graph.addNode(node4);
        graph.addNode(node5);
        graph.addNode(node6);


        // Perform depth-first traversal starting from node1
        List<Node> traversalResult = graph.depthFirst(node1);

        // Display
        System.out.println("Depth-First Traversal Result:");
        for (Node node : traversalResult) {
            System.out.print(node.getValue() + " ");
        }

    }
}
