/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc17;

import DataStructures.tree.Node;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testBreadthFirstTraversal() {
        Node root = new Node(2);
        root.setLeft(new Node(7));
        root.setRight(new Node(5));
        root.getLeft().setLeft(new Node(2));
        root.getLeft().setRight(new Node(6));
        root.getRight().setRight(new Node(9));
        root.getLeft().getRight().setLeft(new Node(5));
        root.getLeft().getRight().setRight(new Node(11));
        root.getRight().getRight().setLeft(new Node(4));

        List<Integer> result = App.breadthFirst(root);

        List<Integer> expected = Arrays.asList(2, 7, 5, 2, 6, 9, 5, 11, 4);

        assertEquals(expected, result);
    }
}
