/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc10;

import LinkedListDataStructure.queue.Queue;
import LinkedListDataStructure.stack.Stack;

public class App {

    public static void main(String[] args) {


        Stack stack=new Stack();
        stack.push(20);
        stack.push(15);
        stack.push(55);

        System.out.println("The full stack=  "+ stack);

        int poppedValue1 = stack.pop();
        System.out.println("The deleted value=" + poppedValue1);
        System.out.println("The stack after popping ="+ stack );

        System.out.println("The peeked value = "+ stack.peek());


        Queue queue=new Queue();
        queue.enqueue(100);
        queue.enqueue(30);
        queue.enqueue(250);
        queue.enqueue(70);

        System.out.println("Queue list = "+ queue);

        System.out.println("Element will be dequeued = "+ queue.dequeue());
        System.out.println("Queue after dequeue from the front = "+ queue);





    }
}
