/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {

    public static void main(String[] args) {
        Graph graph = new Graph();

        // Add vertices
        Vertex vertexA = graph.addVertex("A");
        Vertex vertexB = graph.addVertex("B");
        Vertex vertexC = graph.addVertex("C");

        // Add edges with weights
        graph.addEdge("A", "B", 2);
        graph.addEdge("B", "C", 1);
        graph.addEdge("C", "A", 4);

        // Get vertices
        System.out.println("Vertices: " + graph.getVertices());

        // Get neighbors of a vertex
        System.out.println("Neighbors of B: " + graph.getNeighbors("B"));

        // Get the size of the graph
        System.out.println("Graph size: " + graph.size());

    }
}
