/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc33.hashmap;


import java.util.Map;

public class App {

    public static void main(String[] args) {
        HashMap<String, String> myHashMap = new HashMap<>(10);

        Map<String, String> synonymsMap = new java.util.HashMap<>();
        synonymsMap.put("diligent", "employed");
        synonymsMap.put("fond", "enamored");
        synonymsMap.put("guide", "usher");
        synonymsMap.put("outfit", "garb");
        synonymsMap.put("wrath", "anger");

        Map<String, String> antonymsMap = new java.util.HashMap<>();
        antonymsMap.put("diligent", "idle");
        antonymsMap.put("fond", "averse");
        antonymsMap.put("guide", "follow");
        antonymsMap.put("flow", "jam");
        antonymsMap.put("wrath", "delight");

        Map<String, String[]> result = myHashMap.leftJoin(synonymsMap, antonymsMap);

        for (Map.Entry<String, String[]> entry : result.entrySet()) {
            String key = entry.getKey();
            String[] values = entry.getValue();
            System.out.println("Key: " + key + ", Synonym: " + values[0] + ", Antonym: " + values[1]);
        }
    }
}

