/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc11;

import LinkedListDataStructure.linkedlist.queue.PseudoQueue;

public class App {


    public static void main(String[] args) {
        PseudoQueue<Integer> pseudoQueue = new PseudoQueue<>();

        pseudoQueue.enqueue(1);
        pseudoQueue.enqueue(2);
        pseudoQueue.enqueue(3);

        System.out.println("Dequeue: " + pseudoQueue.dequeue());
        System.out.println("Dequeue: " + pseudoQueue.dequeue());
    }


    }

