/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc11;

public class App {

    public static void main(String[] args) {

        AnimalShelter shelter = new AnimalShelter();

        shelter.enqueue("dog", "Buddy");
        shelter.enqueue("cat", "Whiskers");
        shelter.enqueue("dog", "Max");

        System.out.println(shelter.dequeue("dog").getName());
        System.out.println(shelter.dequeue("cat").getName());
    }
}
