/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.challenges.cc5;

import LinkedListDataStructire.java.LinkedList;
import LinkedListDataStructire.java.Node;

public class App {

    public static void main(String[] args) {
        LinkedList list = new LinkedList();

        list.insert(3);
        list.insert(7);
        list.insert(10);

        Node current = list.head;
        while (current != null) {
            System.out.print(current.value + " -> ");
            current = current.next;
        }
        System.out.println("NULL");
        System.out.println("Value 7 exists in the list: " + list.includes(7));
        System.out.println("Value 5 exists in the list: " + list.includes(5));
        System.out.println(list.toString());
    }



}
