/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc42;

import static challenge.cc42.UrlSanitizer.sanitizeUrl;

public class App {


    public static void main(String[] args) {

        String originalUrl = "https://example.com/path with spaces/page";
        String sanitizedUrl = sanitizeUrl(originalUrl);
        System.out.println("Original URL: " + originalUrl);
        System.out.println("Sanitized URL: " + sanitizedUrl);

    }
}
