/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import DataStructures.tree.BinarySearchTree;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testFizzBuzzTree() {
        BinarySearchTree bst = new BinarySearchTree();
        bst.add(15);
        bst.add(9);
        bst.add(20);
        bst.add(7);

        BinarySearchTree.FizzBuzzNode fizzBuzzRoot = bst.fizzBuzzTree((BinarySearchTree.FizzBuzzNode) bst.getRoot());
        assertEquals("FizzBuzz", fizzBuzzRoot.getValue());
        assertEquals("Fizz", fizzBuzzRoot.getLeft().getValue());
        assertEquals("Buzz", fizzBuzzRoot.getRight().getValue());
        assertEquals("7", fizzBuzzRoot.getLeft().getLeft().getValue());
    }
}
