/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc11;

import LinkedListDataStructure.linkedlist.queue.PseudoQueue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    PseudoQueue<Integer> pseudoQueue;

    @BeforeEach
    public void setUp() {
        pseudoQueue = new PseudoQueue<>();
    }


    @Test
    public void testEnqueueAndDequeue() {
        pseudoQueue.enqueue(1);
        pseudoQueue.enqueue(2);
        pseudoQueue.enqueue(3);

        assertEquals(1, pseudoQueue.dequeue());
        assertEquals(2, pseudoQueue.dequeue());
        assertEquals(3, pseudoQueue.dequeue());
        assertTrue(pseudoQueue.isEmpty());
    }

    @Test
    public void testEnqueueAndDequeueMixed() {
        pseudoQueue.enqueue(1);
        pseudoQueue.enqueue(2);

        assertEquals(1, pseudoQueue.dequeue());

        pseudoQueue.enqueue(3);
        pseudoQueue.enqueue(4);

        assertEquals(2, pseudoQueue.dequeue());

        pseudoQueue.enqueue(5);

        assertEquals(3, pseudoQueue.dequeue());
        assertEquals(4, pseudoQueue.dequeue());
        assertEquals(5, pseudoQueue.dequeue());
        assertTrue(pseudoQueue.isEmpty());
    }

    @Test
    public void testEmptyQueue() {
        assertTrue(pseudoQueue.isEmpty());

        assertThrows(IllegalStateException.class, () -> pseudoQueue.dequeue());
    }
}
