/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

public class App {

    public static void main(String[] args) {
        int[] arr = {8, 4, 23, 42, 16, 15};
        MergeSort.mergeSort(arr);

        System.out.print("Sorted array: ");
        for (int value : arr) {
            System.out.print(value + " ");
        }
    }
}

