/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.HashMap;

import static graph.Graph.businessTrip;


public class App {


    public static void main(String[] args) {
        HashMap<String, HashMap<String, Integer>> flights = new HashMap<>();
        flights.put("Metroville", new HashMap<String, Integer>(){{put("Pandora", 82);}});
        flights.put("Arendelle", new HashMap<String, Integer>(){{put("New Monstropolis", 45);}});
        flights.put("New Monstropolis", new HashMap<String, Integer>(){{put("Naboo", 70);}});
        flights.put("Naboo", new HashMap<String, Integer>(){{put("Pandora", 90);}});

        String[] trip1 = {"Metroville", "Pandora"};
        String[] trip2 = {"Arendelle", "New Monstropolis", "Naboo"};
        String[] trip3 = {"Narnia", "Arendelle", "Naboo"};

        System.out.println(businessTrip(flights, trip1));
        System.out.println(businessTrip(flights, trip2));
        System.out.println(businessTrip(flights, trip3));
    }
}
