/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc16;

import DataStructures.tree.BinaryTree;
import DataStructures.tree.Node;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testFindMaximumValue() {
    Node root = new Node(10);

        root.setLeft(new Node(5));
        root.setRight(new Node(20));
        root.getLeft().setLeft(new Node(3));
        root.getLeft().setRight(new Node(8));
        root.getRight().setLeft(new Node(15));
        root.getRight().setRight(new Node(25));


    BinaryTree binaryTree = new BinaryTree();
        binaryTree.setRoot(root);

        int maxValue = binaryTree.findMaximumValue();

        assertEquals(25, maxValue);
    }
}

