/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc31.hashmap;

public class App {

    public static void main(String[] args) {

        HashMap<String, Integer> hashMap = new HashMap<>(16);


        String text1 = "Once upon a time, there was a brave princess who...";
        String text2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        String text3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        String text4 = "Hello, I'm Balqees";


        String result1 = hashMap.repeatedWord(text1);
        String result2 = hashMap.repeatedWord(text2);
        String result3 = hashMap.repeatedWord(text3);
        String result4 = hashMap.repeatedWord(text4);


        System.out.println("Repeated word in text1: " + result1);
        System.out.println("Repeated word in text2: " + result2);
        System.out.println("Repeated word in text3: " + result3);
        System.out.println("Repeated word in text4: " + result4);

    }
    }
