/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc13;

import static challenge.cc13.BracketsValidator.validateBrackets;

public class App {


    public static void main(String[] args) {
        String input1 = "{}";
        String input2 = "{}(){}";
        String input3 = "{(){}";

        System.out.println(validateBrackets(input1));
        System.out.println(validateBrackets(input2));
        System.out.println(validateBrackets(input3));

    }
    }

