/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge.cc41;

import static challenge.cc41.AnagramValidator.areAnagrams;

public class App {

    public static void main(String[] args) {


        String str1 = "listen";
        String str2 = "silent";

        if (areAnagrams(str1, str2)) {
            System.out.println(str1 + " and " + str2 + " are anagrams.");
        } else {
            System.out.println(str1 + " and " + str2 + " are not anagrams.");
        }

    }
}
