/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import DataStructures.tree.BinarySearchTree;
import DataStructures.tree.BinaryTree;

import java.util.List;

public class App {


    public static void main(String[] args) {


        BinarySearchTree BST = new BinarySearchTree();
        BST.add(3);
        BST.add(5);
        BST.add(15);
        BST.add(7);
        BinaryTree.FizzBuzzNode fizzBuzzRoot = BST.fizzBuzzTree(BST.getRoot());
        List<String> preOrderResult = BST.preOrderTraversal(fizzBuzzRoot);
        for (String value : preOrderResult) {
            System.out.println(value);
        }
    }
    }
