/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testMergeSort() {
        int[] arr = {8, 4, 23, 42, 16, 15};
        int[] expected = {4, 8, 15, 16, 23, 42};

        MergeSort.mergeSort(arr);

        assertArrayEquals(expected, arr);
    }

    @Test
    public void testMergeSortWithSingleElement() {
        int[] arr = {5};
        int[] expected = {5};

        MergeSort.mergeSort(arr);

        assertArrayEquals(expected, arr);
    }



    @Test
    public void testMergeSortWithEmptyArray() {
        int[] arr = {};
        int[] expected = {};

        MergeSort.mergeSort(arr);

        assertArrayEquals(expected, arr);
    }


    @Test
    public void testMergeSortWithNegativeNumbers() {
        int[] arr = {-2, -5, 0, 1, -3};
        int[] expected = {-5, -3, -2, 0, 1};

        MergeSort.mergeSort(arr);

        assertArrayEquals(expected, arr);
    }
}
